//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PseudoCode.Core {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class strings {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal strings() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("PseudoCode.Core.strings", typeof(strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string PseudoCodeInterpreter_ExitFileInput_OperationsStart {
            get {
                return ResourceManager.GetString("PseudoCodeInterpreter_ExitFileInput_OperationsStart", resourceCulture);
            }
        }
        
        internal static string AssignmentOperation_ToPlainString {
            get {
                return ResourceManager.GetString("AssignmentOperation_ToPlainString", resourceCulture);
            }
        }
        
        internal static string Error_ToString {
            get {
                return ResourceManager.GetString("Error_ToString", resourceCulture);
            }
        }
        
        internal static string Type_ThrowUnsupported {
            get {
                return ResourceManager.GetString("Type_ThrowUnsupported", resourceCulture);
            }
        }
        
        internal static string and {
            get {
                return ResourceManager.GetString("and", resourceCulture);
            }
        }
        
        internal static string Type_MakeUnsupportedCastError {
            get {
                return ResourceManager.GetString("Type_MakeUnsupportedCastError", resourceCulture);
            }
        }
        
        internal static string ArrayType_Assign_InvalidArrayLength {
            get {
                return ResourceManager.GetString("ArrayType_Assign_InvalidArrayLength", resourceCulture);
            }
        }
        
        internal static string ArrayType_Index_IndexNotArray {
            get {
                return ResourceManager.GetString("ArrayType_Index_IndexNotArray", resourceCulture);
            }
        }
        
        internal static string ArrayType_Index_InvalidArrayAccessDimension {
            get {
                return ResourceManager.GetString("ArrayType_Index_InvalidArrayAccessDimension", resourceCulture);
            }
        }
        
        internal static string DeclareOperation_Operate_AlreadyDeclared {
            get {
                return ResourceManager.GetString("DeclareOperation_Operate_AlreadyDeclared", resourceCulture);
            }
        }
        
        internal static string Scope_ToPlainString_GlobalScope {
            get {
                return ResourceManager.GetString("Scope_ToPlainString_GlobalScope", resourceCulture);
            }
        }
        
        internal static string Scope_ToPlainString_AnonymousScope {
            get {
                return ResourceManager.GetString("Scope_ToPlainString_AnonymousScope", resourceCulture);
            }
        }
        
        internal static string Error_Name {
            get {
                return ResourceManager.GetString("Error_Name", resourceCulture);
            }
        }
        
        internal static string InvalidAccessError_Name {
            get {
                return ResourceManager.GetString("InvalidAccessError_Name", resourceCulture);
            }
        }
        
        internal static string InvalidTypeError_Name {
            get {
                return ResourceManager.GetString("InvalidTypeError_Name", resourceCulture);
            }
        }
        
        internal static string UnsupportedCastError_Name {
            get {
                return ResourceManager.GetString("UnsupportedCastError_Name", resourceCulture);
            }
        }
        
        internal static string Scope_FindInstanceAddress_NotFound {
            get {
                return ResourceManager.GetString("Scope_FindInstanceAddress_NotFound", resourceCulture);
            }
        }
        
        internal static string ArrayIndexOperation_ToPlainString {
            get {
                return ResourceManager.GetString("ArrayIndexOperation_ToPlainString", resourceCulture);
            }
        }
        
        internal static string BinaryOperation_ToPlainString {
            get {
                return ResourceManager.GetString("BinaryOperation_ToPlainString", resourceCulture);
            }
        }
        
        internal static string DeclareOperation_ToPlainString {
            get {
                return ResourceManager.GetString("DeclareOperation_ToPlainString", resourceCulture);
            }
        }
        
        internal static string FormImmediateArrayOperation_ToPlainString {
            get {
                return ResourceManager.GetString("FormImmediateArrayOperation_ToPlainString", resourceCulture);
            }
        }
        
        internal static string IfOperation_ToString {
            get {
                return ResourceManager.GetString("IfOperation_ToString", resourceCulture);
            }
        }
        
        internal static string IfOperation_ToString_Else {
            get {
                return ResourceManager.GetString("IfOperation_ToString_Else", resourceCulture);
            }
        }
        
        internal static string InputOperation_ToPlainString {
            get {
                return ResourceManager.GetString("InputOperation_ToPlainString", resourceCulture);
            }
        }
        
        internal static string LoadImmediateOperation_ToPlainString {
            get {
                return ResourceManager.GetString("LoadImmediateOperation_ToPlainString", resourceCulture);
            }
        }
        
        internal static string LoadOperation_ToPlainString {
            get {
                return ResourceManager.GetString("LoadOperation_ToPlainString", resourceCulture);
            }
        }
        
        internal static string Operation_ToPlainString {
            get {
                return ResourceManager.GetString("Operation_ToPlainString", resourceCulture);
            }
        }
        
        internal static string OutputOperation_ToPlainString {
            get {
                return ResourceManager.GetString("OutputOperation_ToPlainString", resourceCulture);
            }
        }
        
        internal static string RepeatOperation_ToString_While {
            get {
                return ResourceManager.GetString("RepeatOperation_ToString_While", resourceCulture);
            }
        }
        
        internal static string RepeatOperation_ToString_Repeat {
            get {
                return ResourceManager.GetString("RepeatOperation_ToString_Repeat", resourceCulture);
            }
        }
        
        internal static string UnaryOperation_ToPlainString {
            get {
                return ResourceManager.GetString("UnaryOperation_ToPlainString", resourceCulture);
            }
        }
        
        internal static string Operation_Operate {
            get {
                return ResourceManager.GetString("Operation_Operate", resourceCulture);
            }
        }
        
        internal static string PlaceholderType_ThrowUnsupported_PossibleCauses_AssignBeforeUse {
            get {
                return ResourceManager.GetString("PlaceholderType_ThrowUnsupported_PossibleCauses_AssignBeforeUse", resourceCulture);
            }
        }
        
        internal static string ArrayType_Assign_InvalidValueType {
            get {
                return ResourceManager.GetString("ArrayType_Assign_InvalidValueType", resourceCulture);
            }
        }
        
        internal static string ForOperation_ToString {
            get {
                return ResourceManager.GetString("ForOperation_ToString", resourceCulture);
            }
        }
        
        internal static string AssignmentOperation_ToPlainString_Keep {
            get {
                return ResourceManager.GetString("AssignmentOperation_ToPlainString_Keep", resourceCulture);
            }
        }
        
        internal static string OutOfBoundsError_Name {
            get {
                return ResourceManager.GetString("OutOfBoundsError_Name", resourceCulture);
            }
        }
        
        internal static string ArrayInstance_ElementAt_OutOfBounds {
            get {
                return ResourceManager.GetString("ArrayInstance_ElementAt_OutOfBounds", resourceCulture);
            }
        }
    }
}
