//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.10.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from PseudoCode.g4 by ANTLR 4.10.1

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419


using PseudoCode.Core.Runtime;
using Range = PseudoCode.Core.Runtime.Range;
using System.Globalization;
using PseudoCode.Core.Runtime.Types;

using Antlr4.Runtime.Misc;
using IParseTreeListener = Antlr4.Runtime.Tree.IParseTreeListener;
using IToken = Antlr4.Runtime.IToken;

/// <summary>
/// This interface defines a complete listener for a parse tree produced by
/// <see cref="PseudoCodeParser"/>.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.10.1")]
[System.CLSCompliant(false)]
public interface IPseudoCodeListener : IParseTreeListener {
	/// <summary>
	/// Enter a parse tree produced by <see cref="PseudoCodeParser.fileInput"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterFileInput([NotNull] PseudoCodeParser.FileInputContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PseudoCodeParser.fileInput"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitFileInput([NotNull] PseudoCodeParser.FileInputContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="PseudoCodeParser.singleInput"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterSingleInput([NotNull] PseudoCodeParser.SingleInputContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PseudoCodeParser.singleInput"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitSingleInput([NotNull] PseudoCodeParser.SingleInputContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="PseudoCodeParser.statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterStatement([NotNull] PseudoCodeParser.StatementContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PseudoCodeParser.statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitStatement([NotNull] PseudoCodeParser.StatementContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="PseudoCodeParser.simpleStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterSimpleStatement([NotNull] PseudoCodeParser.SimpleStatementContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PseudoCodeParser.simpleStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitSimpleStatement([NotNull] PseudoCodeParser.SimpleStatementContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="PseudoCodeParser.smallStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterSmallStatement([NotNull] PseudoCodeParser.SmallStatementContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PseudoCodeParser.smallStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitSmallStatement([NotNull] PseudoCodeParser.SmallStatementContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="PseudoCodeParser.assignmentStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterAssignmentStatement([NotNull] PseudoCodeParser.AssignmentStatementContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PseudoCodeParser.assignmentStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitAssignmentStatement([NotNull] PseudoCodeParser.AssignmentStatementContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="PseudoCodeParser.declarationStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterDeclarationStatement([NotNull] PseudoCodeParser.DeclarationStatementContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PseudoCodeParser.declarationStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitDeclarationStatement([NotNull] PseudoCodeParser.DeclarationStatementContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="PseudoCodeParser.constantStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterConstantStatement([NotNull] PseudoCodeParser.ConstantStatementContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PseudoCodeParser.constantStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitConstantStatement([NotNull] PseudoCodeParser.ConstantStatementContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="PseudoCodeParser.ioStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterIoStatement([NotNull] PseudoCodeParser.IoStatementContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PseudoCodeParser.ioStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitIoStatement([NotNull] PseudoCodeParser.IoStatementContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="PseudoCodeParser.returnStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterReturnStatement([NotNull] PseudoCodeParser.ReturnStatementContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PseudoCodeParser.returnStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitReturnStatement([NotNull] PseudoCodeParser.ReturnStatementContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="PseudoCodeParser.callStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterCallStatement([NotNull] PseudoCodeParser.CallStatementContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PseudoCodeParser.callStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitCallStatement([NotNull] PseudoCodeParser.CallStatementContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="PseudoCodeParser.fileStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterFileStatement([NotNull] PseudoCodeParser.FileStatementContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PseudoCodeParser.fileStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitFileStatement([NotNull] PseudoCodeParser.FileStatementContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="PseudoCodeParser.compoundStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterCompoundStatement([NotNull] PseudoCodeParser.CompoundStatementContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PseudoCodeParser.compoundStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitCompoundStatement([NotNull] PseudoCodeParser.CompoundStatementContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="PseudoCodeParser.scopedExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterScopedExpression([NotNull] PseudoCodeParser.ScopedExpressionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PseudoCodeParser.scopedExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitScopedExpression([NotNull] PseudoCodeParser.ScopedExpressionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="PseudoCodeParser.indentedBlock"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterIndentedBlock([NotNull] PseudoCodeParser.IndentedBlockContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PseudoCodeParser.indentedBlock"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitIndentedBlock([NotNull] PseudoCodeParser.IndentedBlockContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="PseudoCodeParser.alignedBlock"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterAlignedBlock([NotNull] PseudoCodeParser.AlignedBlockContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PseudoCodeParser.alignedBlock"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitAlignedBlock([NotNull] PseudoCodeParser.AlignedBlockContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="PseudoCodeParser.ifStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterIfStatement([NotNull] PseudoCodeParser.IfStatementContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PseudoCodeParser.ifStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitIfStatement([NotNull] PseudoCodeParser.IfStatementContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="PseudoCodeParser.forStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterForStatement([NotNull] PseudoCodeParser.ForStatementContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PseudoCodeParser.forStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitForStatement([NotNull] PseudoCodeParser.ForStatementContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="PseudoCodeParser.whileStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterWhileStatement([NotNull] PseudoCodeParser.WhileStatementContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PseudoCodeParser.whileStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitWhileStatement([NotNull] PseudoCodeParser.WhileStatementContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="PseudoCodeParser.repeatStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterRepeatStatement([NotNull] PseudoCodeParser.RepeatStatementContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PseudoCodeParser.repeatStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitRepeatStatement([NotNull] PseudoCodeParser.RepeatStatementContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="PseudoCodeParser.namespaceStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterNamespaceStatement([NotNull] PseudoCodeParser.NamespaceStatementContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PseudoCodeParser.namespaceStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitNamespaceStatement([NotNull] PseudoCodeParser.NamespaceStatementContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="PseudoCodeParser.useNamespaceStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterUseNamespaceStatement([NotNull] PseudoCodeParser.UseNamespaceStatementContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PseudoCodeParser.useNamespaceStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitUseNamespaceStatement([NotNull] PseudoCodeParser.UseNamespaceStatementContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="PseudoCodeParser.caseStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterCaseStatement([NotNull] PseudoCodeParser.CaseStatementContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PseudoCodeParser.caseStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitCaseStatement([NotNull] PseudoCodeParser.CaseStatementContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="PseudoCodeParser.caseBranch"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterCaseBranch([NotNull] PseudoCodeParser.CaseBranchContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PseudoCodeParser.caseBranch"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitCaseBranch([NotNull] PseudoCodeParser.CaseBranchContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="PseudoCodeParser.caseBody"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterCaseBody([NotNull] PseudoCodeParser.CaseBodyContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PseudoCodeParser.caseBody"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitCaseBody([NotNull] PseudoCodeParser.CaseBodyContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="PseudoCodeParser.valueRange"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterValueRange([NotNull] PseudoCodeParser.ValueRangeContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PseudoCodeParser.valueRange"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitValueRange([NotNull] PseudoCodeParser.ValueRangeContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="PseudoCodeParser.externFunctionDefinition"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterExternFunctionDefinition([NotNull] PseudoCodeParser.ExternFunctionDefinitionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PseudoCodeParser.externFunctionDefinition"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitExternFunctionDefinition([NotNull] PseudoCodeParser.ExternFunctionDefinitionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="PseudoCodeParser.procedureDefinition"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterProcedureDefinition([NotNull] PseudoCodeParser.ProcedureDefinitionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PseudoCodeParser.procedureDefinition"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitProcedureDefinition([NotNull] PseudoCodeParser.ProcedureDefinitionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="PseudoCodeParser.functionDefinition"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterFunctionDefinition([NotNull] PseudoCodeParser.FunctionDefinitionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PseudoCodeParser.functionDefinition"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitFunctionDefinition([NotNull] PseudoCodeParser.FunctionDefinitionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="PseudoCodeParser.argumentsDeclaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterArgumentsDeclaration([NotNull] PseudoCodeParser.ArgumentsDeclarationContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PseudoCodeParser.argumentsDeclaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitArgumentsDeclaration([NotNull] PseudoCodeParser.ArgumentsDeclarationContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="PseudoCodeParser.argumentDeclaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterArgumentDeclaration([NotNull] PseudoCodeParser.ArgumentDeclarationContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PseudoCodeParser.argumentDeclaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitArgumentDeclaration([NotNull] PseudoCodeParser.ArgumentDeclarationContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="PseudoCodeParser.genericUtilisation"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterGenericUtilisation([NotNull] PseudoCodeParser.GenericUtilisationContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PseudoCodeParser.genericUtilisation"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitGenericUtilisation([NotNull] PseudoCodeParser.GenericUtilisationContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="PseudoCodeParser.genericDeclaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterGenericDeclaration([NotNull] PseudoCodeParser.GenericDeclarationContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PseudoCodeParser.genericDeclaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitGenericDeclaration([NotNull] PseudoCodeParser.GenericDeclarationContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="PseudoCodeParser.tuple"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterTuple([NotNull] PseudoCodeParser.TupleContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PseudoCodeParser.tuple"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitTuple([NotNull] PseudoCodeParser.TupleContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="PseudoCodeParser.dataTypeList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterDataTypeList([NotNull] PseudoCodeParser.DataTypeListContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PseudoCodeParser.dataTypeList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitDataTypeList([NotNull] PseudoCodeParser.DataTypeListContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="PseudoCodeParser.identifierList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterIdentifierList([NotNull] PseudoCodeParser.IdentifierListContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PseudoCodeParser.identifierList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitIdentifierList([NotNull] PseudoCodeParser.IdentifierListContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="PseudoCodeParser.enumDefinition"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterEnumDefinition([NotNull] PseudoCodeParser.EnumDefinitionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PseudoCodeParser.enumDefinition"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitEnumDefinition([NotNull] PseudoCodeParser.EnumDefinitionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="PseudoCodeParser.enumBody"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterEnumBody([NotNull] PseudoCodeParser.EnumBodyContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PseudoCodeParser.enumBody"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitEnumBody([NotNull] PseudoCodeParser.EnumBodyContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="PseudoCodeParser.typeAliasDefinition"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterTypeAliasDefinition([NotNull] PseudoCodeParser.TypeAliasDefinitionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PseudoCodeParser.typeAliasDefinition"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitTypeAliasDefinition([NotNull] PseudoCodeParser.TypeAliasDefinitionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="PseudoCodeParser.typeDefinition"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterTypeDefinition([NotNull] PseudoCodeParser.TypeDefinitionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PseudoCodeParser.typeDefinition"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitTypeDefinition([NotNull] PseudoCodeParser.TypeDefinitionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="PseudoCodeParser.typeBody"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterTypeBody([NotNull] PseudoCodeParser.TypeBodyContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PseudoCodeParser.typeBody"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitTypeBody([NotNull] PseudoCodeParser.TypeBodyContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="PseudoCodeParser.typeChild"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterTypeChild([NotNull] PseudoCodeParser.TypeChildContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PseudoCodeParser.typeChild"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitTypeChild([NotNull] PseudoCodeParser.TypeChildContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="PseudoCodeParser.classDefinition"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterClassDefinition([NotNull] PseudoCodeParser.ClassDefinitionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PseudoCodeParser.classDefinition"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitClassDefinition([NotNull] PseudoCodeParser.ClassDefinitionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="PseudoCodeParser.classBody"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterClassBody([NotNull] PseudoCodeParser.ClassBodyContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PseudoCodeParser.classBody"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitClassBody([NotNull] PseudoCodeParser.ClassBodyContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="PseudoCodeParser.classDataMember"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterClassDataMember([NotNull] PseudoCodeParser.ClassDataMemberContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PseudoCodeParser.classDataMember"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitClassDataMember([NotNull] PseudoCodeParser.ClassDataMemberContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="PseudoCodeParser.classMethod"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterClassMethod([NotNull] PseudoCodeParser.ClassMethodContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PseudoCodeParser.classMethod"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitClassMethod([NotNull] PseudoCodeParser.ClassMethodContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="PseudoCodeParser.accessLevel"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterAccessLevel([NotNull] PseudoCodeParser.AccessLevelContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PseudoCodeParser.accessLevel"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitAccessLevel([NotNull] PseudoCodeParser.AccessLevelContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="PseudoCodeParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterExpression([NotNull] PseudoCodeParser.ExpressionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PseudoCodeParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitExpression([NotNull] PseudoCodeParser.ExpressionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="PseudoCodeParser.logicExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterLogicExpression([NotNull] PseudoCodeParser.LogicExpressionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PseudoCodeParser.logicExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitLogicExpression([NotNull] PseudoCodeParser.LogicExpressionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="PseudoCodeParser.arithmeticExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterArithmeticExpression([NotNull] PseudoCodeParser.ArithmeticExpressionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PseudoCodeParser.arithmeticExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitArithmeticExpression([NotNull] PseudoCodeParser.ArithmeticExpressionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="PseudoCodeParser.arguments"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterArguments([NotNull] PseudoCodeParser.ArgumentsContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PseudoCodeParser.arguments"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitArguments([NotNull] PseudoCodeParser.ArgumentsContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="PseudoCodeParser.atom"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterAtom([NotNull] PseudoCodeParser.AtomContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PseudoCodeParser.atom"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitAtom([NotNull] PseudoCodeParser.AtomContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="PseudoCodeParser.dataType"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterDataType([NotNull] PseudoCodeParser.DataTypeContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PseudoCodeParser.dataType"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitDataType([NotNull] PseudoCodeParser.DataTypeContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="PseudoCodeParser.basicDataType"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterBasicDataType([NotNull] PseudoCodeParser.BasicDataTypeContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PseudoCodeParser.basicDataType"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitBasicDataType([NotNull] PseudoCodeParser.BasicDataTypeContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="PseudoCodeParser.modularDataType"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterModularDataType([NotNull] PseudoCodeParser.ModularDataTypeContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PseudoCodeParser.modularDataType"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitModularDataType([NotNull] PseudoCodeParser.ModularDataTypeContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="PseudoCodeParser.typeLookup"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterTypeLookup([NotNull] PseudoCodeParser.TypeLookupContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PseudoCodeParser.typeLookup"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitTypeLookup([NotNull] PseudoCodeParser.TypeLookupContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="PseudoCodeParser.arrayRange"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterArrayRange([NotNull] PseudoCodeParser.ArrayRangeContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PseudoCodeParser.arrayRange"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitArrayRange([NotNull] PseudoCodeParser.ArrayRangeContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="PseudoCodeParser.array"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterArray([NotNull] PseudoCodeParser.ArrayContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PseudoCodeParser.array"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitArray([NotNull] PseudoCodeParser.ArrayContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="PseudoCodeParser.number"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterNumber([NotNull] PseudoCodeParser.NumberContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PseudoCodeParser.number"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitNumber([NotNull] PseudoCodeParser.NumberContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="PseudoCodeParser.decimal"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterDecimal([NotNull] PseudoCodeParser.DecimalContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PseudoCodeParser.decimal"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitDecimal([NotNull] PseudoCodeParser.DecimalContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="PseudoCodeParser.integer"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterInteger([NotNull] PseudoCodeParser.IntegerContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PseudoCodeParser.integer"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitInteger([NotNull] PseudoCodeParser.IntegerContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="PseudoCodeParser.identifierWithNew"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterIdentifierWithNew([NotNull] PseudoCodeParser.IdentifierWithNewContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PseudoCodeParser.identifierWithNew"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitIdentifierWithNew([NotNull] PseudoCodeParser.IdentifierWithNewContext context);
}
